### ISSUE TITLE
exiting with incorrect api_key or access_token

### ISSUE THREAD

**Issue by mraghu4** [mraghu4/TradeAuto#7]
$ python3 start_trade.py
2022-03-11 09:28:02,597 [INFO] : Intraday Stradel with SL and trail remaining SL when one of SL is executed

Traceback (most recent call last):
  File "start_trade.py", line 114, in <module>
    main()
  File "start_trade.py", line 109, in main
    strategy.start_trade(kite,inputs)
  File "/home/raghu/TradeAuto/strategies/options/intraday_stradel/opt_intraday_sl_stradel_strategy.py", line 383, in start_trade
    self.execute_strategy()
  File "/home/raghu/TradeAuto/strategies/options/intraday_stradel/opt_intraday_sl_stradel_strategy.py", line 372, in execute_strategy
    self.trade_stradel()
  File "/home/raghu/TradeAuto/strategies/options/intraday_stradel/opt_intraday_sl_stradel_strategy.py", line 167, in trade_stradel
    security_price = self.get_security_price(security)
  File "/home/raghu/TradeAuto/strategies/options/intraday_stradel/opt_intraday_sl_stradel_strategy.py", line 85, in get_security_price
    return self.kite.quote(security)[security]["last_price"]
  File "/home/raghu/env/lib64/python3.6/site-packages/kiteconnect/connect.py", line 572, in quote
    data = self._get("market.quote", params={"i": ins})
  File "/home/raghu/env/lib64/python3.6/site-packages/kiteconnect/connect.py", line 837, in _get
    return self._request(route, "GET", url_args=url_args, params=params, is_json=is_json)
  File "/home/raghu/env/lib64/python3.6/site-packages/kiteconnect/connect.py", line 913, in _request
    raise exp(data["message"], code=r.status_code)
kiteconnect.exceptions.TokenException: Incorrect `api_key` or `access_token`.

**Comment by mraghu4** [comment]
This could happen if the token is refreshed from browser in same day or due any other reason... 
delete  "TradeAauto\logs\kite_token" file and retry...
